# Generated by Django 4.1.13 on 2025-01-28 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0003_module_team_remove_ticket_resolved_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketassignment',
            options={},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='type',
            new_name='project_type',
        ),
        migrations.AlterUniqueTogether(
            name='ticketassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketassignment',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Assigned', max_length=20),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('team_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Member', 'Member'), ('Leader', 'Leader')], default='Member', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ticketing.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('team', 'user')},
            },
        ),
    ]
