# Generated by Django 4.1.13 on 2025-01-30 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presalesApp', '0011_projecttype_project_project_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0005_team_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatConvo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chatwindow_id', models.IntegerField()),
                ('user_query', models.TextField()),
                ('response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convo', to='presalesApp.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
