# Generated by Django 4.1.13 on 2025-01-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_teammember_email_alter_teammember_user_chatconvo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
