# Generated by Django 4.1.13 on 2025-02-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketassignment',
            name='comments',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
