# Generated by Django 4.1.13 on 2025-02-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0009_alter_ticketassignment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='solution',
            field=models.CharField(blank=True, default=None, max_length=100000, null=True),
        ),
    ]
