# Generated by Django 4.1.13 on 2025-02-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0011_trackingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='escalation_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketassignment',
            name='email_triggered',
            field=models.BooleanField(default=False),
        ),
    ]
