# Generated by Django 4.1.13 on 2025-03-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0012_ticket_escalation_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconvo',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
